language: cpp
dist: focal
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cppcheck
      - clang-tidy
      - python3-minimal
script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake . -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . -- -j2
  - ctest -j2
  - sh ./static-analysis.sh
  - python3 ./generate_submission_file.py

